DROP DATABASE IF EXISTS lootzone_db;
CREATE DATABASE lootzone_db;
USE lootzone_db;

CREATE TABLE UTENTE (
    ID_Utente INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Data_Registrazione DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AMMINISTRATORE (
    ID_Utente INT PRIMARY KEY,
    Codice_Admin VARCHAR(50) NOT NULL,
    Ruolo_Gestione VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_Utente) REFERENCES UTENTE(ID_Utente) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CLIENTE (
    ID_Utente INT PRIMARY KEY,
    Nickname VARCHAR(50) NOT NULL,
    Preferenze_Genere VARCHAR(255),
    Indirizzo_Spedizione VARCHAR(255),
    FOREIGN KEY (ID_Utente) REFERENCES UTENTE(ID_Utente) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PRODOTTO (
    ID_Prodotto INT AUTO_INCREMENT PRIMARY KEY,
    Titolo VARCHAR(255) NOT NULL,
    Piattaforma VARCHAR(100) NOT NULL,
    Genere VARCHAR(100) NOT NULL,
    Prezzo_Base DECIMAL(10,2) NOT NULL,
    Tipo_Formato VARCHAR(50) NOT NULL,
    Descrizione TEXT,
    Immagine VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ORDINE (
    ID_Ordine INT AUTO_INCREMENT PRIMARY KEY,
    Data_Acquisto DATETIME NOT NULL,
    Totale DECIMAL(10,2) NOT NULL,
    Stato_Spedizione VARCHAR(50) NOT NULL,
    ID_Cliente INT NOT NULL,
    ID_Amministratore INT,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Utente) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Amministratore) REFERENCES AMMINISTRATORE(ID_Utente) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DETTAGLIO_ORDINE (
    ID_Ordine INT NOT NULL,
    ID_Prodotto INT NOT NULL,
    Quantita INT NOT NULL,
    PRIMARY KEY (ID_Ordine, ID_Prodotto),
    FOREIGN KEY (ID_Ordine) REFERENCES ORDINE(ID_Ordine) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Prodotto) REFERENCES PRODOTTO(ID_Prodotto) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PROPOSTA_VENDITA (
    ID_Proposta INT AUTO_INCREMENT PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    Stato VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Utente) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE COPIA_USATA (
    ID_Copia INT AUTO_INCREMENT PRIMARY KEY,
    ID_Prodotto INT NOT NULL,
    Stato_Usura VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_Prodotto) REFERENCES PRODOTTO(ID_Prodotto) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;